import type { MarketValidationPriceBand } from "./contract";

export const MARKET_VALIDATION_DEMO_DATASET_VERSION = "mv2-2026-10-05" as const;

export type MarketValidationDemoListing = Readonly<{
  id: `mv_demo_${string}`;
  producer: string;
  wine: string;
  denomination: string;
  vintage: number;
  format: "0,75 L" | "1,5 L";
  condition: "Ottima" | "Buona";
  price_cents: number;
  image: `/images/${string}`;
  price_band: MarketValidationPriceBand;
  validation_demo: true;
}>;

/**
 * Fixture versionata e non commerciale. Questi record non sono righe di
 * `public.listings`, non hanno un venditore e non possono diventare ordini.
 * Nomi e produttori sono esempi fittizi per la sola Market Validation.
 */
export const MARKET_VALIDATION_DEMO_LISTINGS = [
  {
    id: "mv_demo_riflesso_rosso_2021",
    producer: "Cantina Riflesso",
    wine: "Riflesso Rosso",
    denomination: "Barbera d'Asti DOCG",
    vintage: 2021,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 1800,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_colle_chiaro_2022",
    producer: "Podere Colle Chiaro",
    wine: "Vigna del Mattino",
    denomination: "Langhe Nebbiolo DOC",
    vintage: 2022,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 2100,
    image: "/images/vinea-bottle-2.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_sorgente_bianca_2023",
    producer: "Tenuta Sorgente",
    wine: "Sorgente Bianca",
    denomination: "Soave Classico DOC",
    vintage: 2023,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 2400,
    image: "/images/vinea-white.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_corte_vento_2020",
    producer: "Corte del Vento",
    wine: "Vento di Sera",
    denomination: "Valpolicella Ripasso DOC",
    vintage: 2020,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 2550,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_pietra_lieve_2022",
    producer: "Vigne Pietra Lieve",
    wine: "Pietra Lieve",
    denomination: "Etna Rosso DOC",
    vintage: 2022,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 2700,
    image: "/images/vinea-vineyard.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_prato_dorato_2021",
    producer: "Casa Prato Dorato",
    wine: "Prato Dorato",
    denomination: "Verdicchio dei Castelli di Jesi DOC",
    vintage: 2021,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 2820,
    image: "/images/vinea-white.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_riva_quieta_2020",
    producer: "Cantina Riva Quieta",
    wine: "Riva Quieta",
    denomination: "Chianti Classico DOCG",
    vintage: 2020,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 2910,
    image: "/images/vinea-crate.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_ombra_gentile_2019",
    producer: "Podere Ombra Gentile",
    wine: "Ombra Gentile",
    denomination: "Montepulciano d'Abruzzo DOC",
    vintage: 2019,
    format: "1,5 L",
    condition: "Buona",
    price_cents: 2990,
    image: "/images/vinea-cellar.jpg",
    price_band: "15–30",
    validation_demo: true,
  },
  {
    id: "mv_demo_valle_serena_2020",
    producer: "Tenuta Valle Serena",
    wine: "Riserva Serena",
    denomination: "Nobile di Montepulciano DOCG",
    vintage: 2020,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 3400,
    image: "/images/vinea-bottle-2.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_torre_luna_2019",
    producer: "Vigne Torre Luna",
    wine: "Luna Rossa",
    denomination: "Rosso di Montalcino DOC",
    vintage: 2019,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 3800,
    image: "/images/vinea-label.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_costa_salina_2021",
    producer: "Casa Costa Salina",
    wine: "Breve Mare",
    denomination: "Vermentino di Gallura DOCG",
    vintage: 2021,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 4200,
    image: "/images/vinea-white.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_bosco_alto_2018",
    producer: "Cantina Bosco Alto",
    wine: "Bosco Alto Riserva",
    denomination: "Barolo DOCG",
    vintage: 2018,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 4600,
    image: "/images/vinea-cellar.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_quercia_nuova_2019",
    producer: "Podere Quercia Nuova",
    wine: "Quercia Nuova",
    denomination: "Amarone della Valpolicella DOCG",
    vintage: 2019,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 4900,
    image: "/images/vinea-crate.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_campo_azzurro_2020",
    producer: "Vigne Campo Azzurro",
    wine: "Campo Azzurro",
    denomination: "Bolgheri Rosso DOC",
    vintage: 2020,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 5200,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_fonte_antica_2018",
    producer: "Tenuta Fonte Antica",
    wine: "Fonte Antica",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2018,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 5600,
    image: "/images/vinea-label.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_arco_dorato_2017",
    producer: "Casa Arco Dorato",
    wine: "Arco Dorato Magnum",
    denomination: "Franciacorta DOCG",
    vintage: 2017,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 5900,
    image: "/images/vinea-champagne.jpg",
    price_band: "30–60",
    validation_demo: true,
  },
  {
    id: "mv_demo_cresta_rossa_2018",
    producer: "Cantina Cresta Rossa",
    wine: "Cresta Rossa Riserva",
    denomination: "Barbaresco DOCG",
    vintage: 2018,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 6400,
    image: "/images/vinea-bottle-2.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_via_delle_stelle_2017",
    producer: "Podere Via delle Stelle",
    wine: "Stella Prima",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2017,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 6900,
    image: "/images/vinea-cellar.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_terra_scura_2016",
    producer: "Tenuta Terra Scura",
    wine: "Terra Scura",
    denomination: "Amarone della Valpolicella DOCG",
    vintage: 2016,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 7400,
    image: "/images/vinea-crate.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_nodo_doro_2019",
    producer: "Vigne Nodo d'Oro",
    wine: "Nodo d'Oro",
    denomination: "Bolgheri Superiore DOC",
    vintage: 2019,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 7900,
    image: "/images/vinea-label.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_vento_lungo_2016",
    producer: "Casa Vento Lungo",
    wine: "Vento Lungo Riserva",
    denomination: "Barolo DOCG",
    vintage: 2016,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 8500,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_luce_di_riva_2018",
    producer: "Cantina Luce di Riva",
    wine: "Luce di Riva",
    denomination: "Etna Rosso DOC",
    vintage: 2018,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 9000,
    image: "/images/vinea-vineyard.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_rocca_silente_2015",
    producer: "Tenuta Rocca Silente",
    wine: "Rocca Silente",
    denomination: "Taurasi DOCG",
    vintage: 2015,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 9500,
    image: "/images/vinea-capsule.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_neve_dorata_2016",
    producer: "Maison Neve Dorata",
    wine: "Neve Dorata Millesimato",
    denomination: "Franciacorta DOCG",
    vintage: 2016,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 9900,
    image: "/images/vinea-champagne.jpg",
    price_band: "60–100",
    validation_demo: true,
  },
  {
    id: "mv_demo_cima_serena_2015",
    producer: "Podere Cima Serena",
    wine: "Cima Serena Riserva",
    denomination: "Barolo DOCG",
    vintage: 2015,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 10800,
    image: "/images/vinea-bottle-2.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_giardino_segreto_2016",
    producer: "Tenuta Giardino Segreto",
    wine: "Giardino Segreto",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2016,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 11900,
    image: "/images/vinea-cellar.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_lago_profondo_2014",
    producer: "Cantina Lago Profondo",
    wine: "Lago Profondo",
    denomination: "Amarone della Valpolicella DOCG",
    vintage: 2014,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 13200,
    image: "/images/vinea-crate.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_orizzonte_2015",
    producer: "Vigne Orizzonte",
    wine: "Orizzonte Riserva",
    denomination: "Bolgheri Superiore DOC",
    vintage: 2015,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 14500,
    image: "/images/vinea-label.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_selva_reale_2013",
    producer: "Casa Selva Reale",
    wine: "Selva Reale",
    denomination: "Barbaresco DOCG",
    vintage: 2013,
    format: "1,5 L",
    condition: "Buona",
    price_cents: 15900,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_poggio_raro_2012",
    producer: "Tenuta Poggio Raro",
    wine: "Poggio Raro",
    denomination: "Barolo DOCG",
    vintage: 2012,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 17500,
    image: "/images/vinea-capsule.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_alba_lunga_2014",
    producer: "Cantina Alba Lunga",
    wine: "Alba Lunga Magnum",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2014,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 18800,
    image: "/images/vinea-vineyard.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_filo_dargento_2011",
    producer: "Maison Filo d'Argento",
    wine: "Filo d'Argento Riserva",
    denomination: "Franciacorta DOCG",
    vintage: 2011,
    format: "1,5 L",
    condition: "Buona",
    price_cents: 19900,
    image: "/images/vinea-champagne.jpg",
    price_band: "100–200",
    validation_demo: true,
  },
  {
    id: "mv_demo_torre_antica_2010",
    producer: "Tenuta Torre Antica",
    wine: "Torre Antica",
    denomination: "Barolo DOCG",
    vintage: 2010,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 21500,
    image: "/images/vinea-cellar.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_notte_chiara_2011",
    producer: "Podere Notte Chiara",
    wine: "Notte Chiara Riserva",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2011,
    format: "0,75 L",
    condition: "Buona",
    price_cents: 23500,
    image: "/images/vinea-bottle-2.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_pietra_corona_2009",
    producer: "Cantina Pietra Corona",
    wine: "Pietra Corona",
    denomination: "Amarone della Valpolicella DOCG",
    vintage: 2009,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 26000,
    image: "/images/vinea-crate.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_radice_nobile_2008",
    producer: "Vigne Radice Nobile",
    wine: "Radice Nobile",
    denomination: "Barbaresco DOCG",
    vintage: 2008,
    format: "1,5 L",
    condition: "Buona",
    price_cents: 28500,
    image: "/images/vinea-label.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_corte_imperiale_2007",
    producer: "Casa Corte Imperiale",
    wine: "Corte Imperiale",
    denomination: "Barolo DOCG",
    vintage: 2007,
    format: "0,75 L",
    condition: "Ottima",
    price_cents: 32000,
    image: "/images/vinea-capsule.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_riserva_del_tempo_2006",
    producer: "Tenuta del Tempo",
    wine: "Riserva del Tempo",
    denomination: "Brunello di Montalcino DOCG",
    vintage: 2006,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 36000,
    image: "/images/vinea-vineyard.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_gran_selva_2005",
    producer: "Cantina Gran Selva",
    wine: "Gran Selva",
    denomination: "Bolgheri Superiore DOC",
    vintage: 2005,
    format: "1,5 L",
    condition: "Buona",
    price_cents: 42000,
    image: "/images/vinea-bottle-1.jpg",
    price_band: "200+",
    validation_demo: true,
  },
  {
    id: "mv_demo_oro_del_colle_2004",
    producer: "Podere Oro del Colle",
    wine: "Oro del Colle",
    denomination: "Barolo DOCG",
    vintage: 2004,
    format: "1,5 L",
    condition: "Ottima",
    price_cents: 48500,
    image: "/images/vinea-cellar.jpg",
    price_band: "200+",
    validation_demo: true,
  },
] as const satisfies readonly MarketValidationDemoListing[];
