/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcquistiRouteImport } from './routes/acquisti'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CantinaRouteImport } from './routes/cantina'
import { Route as EsploraRouteImport } from './routes/esplora'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MessaggiRouteImport } from './routes/messaggi'
import { Route as NotificheRouteImport } from './routes/notifiche'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfiloRouteImport } from './routes/profilo'
import { Route as SegnalazioniRouteImport } from './routes/segnalazioni'
import { Route as VendiRouteImport } from './routes/vendi'
import { Route as VenditeRouteImport } from './routes/vendite'
import { Route as VerificaVenditoreRouteImport } from './routes/verifica-venditore'
import { Route as AdminStatiRouteImport } from './routes/admin.stati'
import { Route as AnnuncioIdRouteImport } from './routes/annuncio.$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CommunitySlugRouteImport } from './routes/community.$slug'
import { Route as OrdineIdRouteImport } from './routes/ordine.$id'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as VenditoreUsernameRouteImport } from './routes/venditore.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquistiRoute = AcquistiRouteImport.update({
  id: '/acquisti',
  path: '/acquisti',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CantinaRoute = CantinaRouteImport.update({
  id: '/cantina',
  path: '/cantina',
  getParentRoute: () => rootRouteImport,
} as any)
const EsploraRoute = EsploraRouteImport.update({
  id: '/esplora',
  path: '/esplora',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MessaggiRoute = MessaggiRouteImport.update({
  id: '/messaggi',
  path: '/messaggi',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificheRoute = NotificheRouteImport.update({
  id: '/notifiche',
  path: '/notifiche',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfiloRoute = ProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => rootRouteImport,
} as any)
const SegnalazioniRoute = SegnalazioniRouteImport.update({
  id: '/segnalazioni',
  path: '/segnalazioni',
  getParentRoute: () => rootRouteImport,
} as any)
const VendiRoute = VendiRouteImport.update({
  id: '/vendi',
  path: '/vendi',
  getParentRoute: () => rootRouteImport,
} as any)
const VenditeRoute = VenditeRouteImport.update({
  id: '/vendite',
  path: '/vendite',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificaVenditoreRoute = VerificaVenditoreRouteImport.update({
  id: '/verifica-venditore',
  path: '/verifica-venditore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatiRoute = AdminStatiRouteImport.update({
  id: '/stati',
  path: '/stati',
  getParentRoute: () => AdminRoute,
} as any)
const AnnuncioIdRoute = AnnuncioIdRouteImport.update({
  id: '/annuncio/$id',
  path: '/annuncio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySlugRoute = CommunitySlugRouteImport.update({
  id: '/community/$slug',
  path: '/community/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdineIdRoute = OrdineIdRouteImport.update({
  id: '/ordine/$id',
  path: '/ordine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const VenditoreUsernameRoute = VenditoreUsernameRouteImport.update({
  id: '/venditore/$username',
  path: '/venditore/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisti': typeof AcquistiRoute
  '/admin': typeof AdminRouteWithChildren
  '/cantina': typeof CantinaRoute
  '/esplora': typeof EsploraRoute
  '/home': typeof HomeRoute
  '/messaggi': typeof MessaggiRoute
  '/notifiche': typeof NotificheRoute
  '/onboarding': typeof OnboardingRoute
  '/profilo': typeof ProfiloRoute
  '/segnalazioni': typeof SegnalazioniRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/verifica-venditore': typeof VerificaVenditoreRoute
  '/admin/stati': typeof AdminStatiRoute
  '/annuncio/$id': typeof AnnuncioIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/ordine/$id': typeof OrdineIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/venditore/$username': typeof VenditoreUsernameRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisti': typeof AcquistiRoute
  '/admin': typeof AdminRouteWithChildren
  '/cantina': typeof CantinaRoute
  '/esplora': typeof EsploraRoute
  '/home': typeof HomeRoute
  '/messaggi': typeof MessaggiRoute
  '/notifiche': typeof NotificheRoute
  '/onboarding': typeof OnboardingRoute
  '/profilo': typeof ProfiloRoute
  '/segnalazioni': typeof SegnalazioniRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/verifica-venditore': typeof VerificaVenditoreRoute
  '/admin/stati': typeof AdminStatiRoute
  '/annuncio/$id': typeof AnnuncioIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/ordine/$id': typeof OrdineIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/venditore/$username': typeof VenditoreUsernameRoute
  '/community': typeof CommunityIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisti': typeof AcquistiRoute
  '/admin': typeof AdminRouteWithChildren
  '/cantina': typeof CantinaRoute
  '/esplora': typeof EsploraRoute
  '/home': typeof HomeRoute
  '/messaggi': typeof MessaggiRoute
  '/notifiche': typeof NotificheRoute
  '/onboarding': typeof OnboardingRoute
  '/profilo': typeof ProfiloRoute
  '/segnalazioni': typeof SegnalazioniRoute
  '/vendi': typeof VendiRoute
  '/vendite': typeof VenditeRoute
  '/verifica-venditore': typeof VerificaVenditoreRoute
  '/admin/stati': typeof AdminStatiRoute
  '/annuncio/$id': typeof AnnuncioIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/community/$slug': typeof CommunitySlugRoute
  '/ordine/$id': typeof OrdineIdRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/venditore/$username': typeof VenditoreUsernameRoute
  '/community/': typeof CommunityIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisti'
    | '/admin'
    | '/cantina'
    | '/esplora'
    | '/home'
    | '/messaggi'
    | '/notifiche'
    | '/onboarding'
    | '/profilo'
    | '/segnalazioni'
    | '/vendi'
    | '/vendite'
    | '/verifica-venditore'
    | '/admin/stati'
    | '/annuncio/$id'
    | '/checkout/$id'
    | '/community/$slug'
    | '/ordine/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/venditore/$username'
    | '/community/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisti'
    | '/admin'
    | '/cantina'
    | '/esplora'
    | '/home'
    | '/messaggi'
    | '/notifiche'
    | '/onboarding'
    | '/profilo'
    | '/segnalazioni'
    | '/vendi'
    | '/vendite'
    | '/verifica-venditore'
    | '/admin/stati'
    | '/annuncio/$id'
    | '/checkout/$id'
    | '/community/$slug'
    | '/ordine/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/venditore/$username'
    | '/community'
  id:
    | '__root__'
    | '/'
    | '/acquisti'
    | '/admin'
    | '/cantina'
    | '/esplora'
    | '/home'
    | '/messaggi'
    | '/notifiche'
    | '/onboarding'
    | '/profilo'
    | '/segnalazioni'
    | '/vendi'
    | '/vendite'
    | '/verifica-venditore'
    | '/admin/stati'
    | '/annuncio/$id'
    | '/checkout/$id'
    | '/community/$slug'
    | '/ordine/$id'
    | '/payment/cancel'
    | '/payment/success'
    | '/venditore/$username'
    | '/community/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquistiRoute: typeof AcquistiRoute
  AdminRoute: typeof AdminRouteWithChildren
  CantinaRoute: typeof CantinaRoute
  EsploraRoute: typeof EsploraRoute
  HomeRoute: typeof HomeRoute
  MessaggiRoute: typeof MessaggiRoute
  NotificheRoute: typeof NotificheRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfiloRoute: typeof ProfiloRoute
  SegnalazioniRoute: typeof SegnalazioniRoute
  VendiRoute: typeof VendiRoute
  VenditeRoute: typeof VenditeRoute
  VerificaVenditoreRoute: typeof VerificaVenditoreRoute
  AnnuncioIdRoute: typeof AnnuncioIdRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  CommunitySlugRoute: typeof CommunitySlugRoute
  OrdineIdRoute: typeof OrdineIdRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  VenditoreUsernameRoute: typeof VenditoreUsernameRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisti': {
      id: '/acquisti'
      path: '/acquisti'
      fullPath: '/acquisti'
      preLoaderRoute: typeof AcquistiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cantina': {
      id: '/cantina'
      path: '/cantina'
      fullPath: '/cantina'
      preLoaderRoute: typeof CantinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esplora': {
      id: '/esplora'
      path: '/esplora'
      fullPath: '/esplora'
      preLoaderRoute: typeof EsploraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaggi': {
      id: '/messaggi'
      path: '/messaggi'
      fullPath: '/messaggi'
      preLoaderRoute: typeof MessaggiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifiche': {
      id: '/notifiche'
      path: '/notifiche'
      fullPath: '/notifiche'
      preLoaderRoute: typeof NotificheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profilo': {
      id: '/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof ProfiloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segnalazioni': {
      id: '/segnalazioni'
      path: '/segnalazioni'
      fullPath: '/segnalazioni'
      preLoaderRoute: typeof SegnalazioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendi': {
      id: '/vendi'
      path: '/vendi'
      fullPath: '/vendi'
      preLoaderRoute: typeof VendiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendite': {
      id: '/vendite'
      path: '/vendite'
      fullPath: '/vendite'
      preLoaderRoute: typeof VenditeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifica-venditore': {
      id: '/verifica-venditore'
      path: '/verifica-venditore'
      fullPath: '/verifica-venditore'
      preLoaderRoute: typeof VerificaVenditoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stati': {
      id: '/admin/stati'
      path: '/stati'
      fullPath: '/admin/stati'
      preLoaderRoute: typeof AdminStatiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/annuncio/$id': {
      id: '/annuncio/$id'
      path: '/annuncio/$id'
      fullPath: '/annuncio/$id'
      preLoaderRoute: typeof AnnuncioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$slug': {
      id: '/community/$slug'
      path: '/community/$slug'
      fullPath: '/community/$slug'
      preLoaderRoute: typeof CommunitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordine/$id': {
      id: '/ordine/$id'
      path: '/ordine/$id'
      fullPath: '/ordine/$id'
      preLoaderRoute: typeof OrdineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venditore/$username': {
      id: '/venditore/$username'
      path: '/venditore/$username'
      fullPath: '/venditore/$username'
      preLoaderRoute: typeof VenditoreUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminStatiRoute: typeof AdminStatiRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminStatiRoute: AdminStatiRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquistiRoute: AcquistiRoute,
  AdminRoute: AdminRouteWithChildren,
  CantinaRoute: CantinaRoute,
  EsploraRoute: EsploraRoute,
  HomeRoute: HomeRoute,
  MessaggiRoute: MessaggiRoute,
  NotificheRoute: NotificheRoute,
  OnboardingRoute: OnboardingRoute,
  ProfiloRoute: ProfiloRoute,
  SegnalazioniRoute: SegnalazioniRoute,
  VendiRoute: VendiRoute,
  VenditeRoute: VenditeRoute,
  VerificaVenditoreRoute: VerificaVenditoreRoute,
  AnnuncioIdRoute: AnnuncioIdRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  CommunitySlugRoute: CommunitySlugRoute,
  OrdineIdRoute: OrdineIdRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  VenditoreUsernameRoute: VenditoreUsernameRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
